nameOverride: consumer

replicaCount: 3

image: localhost:5000/demo-consumer

streams:
  brokers: "kafka://demo-cp-kafka-headless:9092"
  schemaRegistryUrl: "http://demo-cp-schema-registry:8081"
  inputTopics:
    - input-topic
  outputTopic: output-topic
  errorTopic: error-topic

debug: true
